using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BREPipelineFramework.SampleInstructions
{
    /// <summary>
    /// See http://msdn.microsoft.com/en-us/library/bb226554.aspx for an explanation of the EDI context properties
    /// </summary>
    public enum BizTalkEDIPropertySchemaEnum
    {
        AgreementID = 0 ,
        AgreementName = 1,
        AgreementNameForSend = 2,
        AgreementPartIDForSend = 3,
        AgreementPartIDOnReceive = 4,
        AK901 = 5,
        AttachmentId = 6,
        BatchElementValidationFailure = 7,
        BatchEncodingType = 8,
        BatchId = 9,
        BatchIds = 10,
        BatchingError = 11,
        BatchName = 12,
        CharacterSet = 13,
        CONTRL_UCI4 = 14,
        ControlActionType = 15,
        DestinationEncodingTypes = 16,
        DestinationParties = 17,
        DestinationPartyId = 18,
        DestinationPartyName = 19,
        DestinationPartyReceiverIdentifier = 20,
        DestinationPartyReceiverQualifier = 21,
        DestinationPartySenderIdentifier = 22,
        DestinationPartySenderQualifier = 23,
        EncodingType = 24,
        ErrorDescription = 25,
        GE01 = 26,
        GS_Segment = 27,
        GS01 = 28,
        GS02 = 29,
        GS03 = 30,
        GS07 = 31,
        GS08 = 32,
        IgnoreEncodingType = 33,
        ISA_Segment = 34,
        ISA05 = 35,
        ISA06 = 36,
        ISA07 = 37,
        ISA08 = 38,
        ISA15 = 39,
        IsResendControlMessage = 40,
        IsSystemGeneratedAck = 41,
        PopulateInterchangeValues = 42,
        ReceiverPartyName = 43,
        ReceiverPartyNameForSend = 44,
        ReuseEnvelope = 45,
        SenderPartyName = 46,
        SenderPartyNameForSend = 47,
        ST01 = 48,
        ST03 = 49,
        StatusReportContinuationId = 50,
        TA1_TA104 = 51,
        ToBeBatched = 52,
        ToBeRouted = 53,
        TsSequenceNumberInGroup = 54,
        UNA_Segment = 55,
        UNB_Segment = 56,
        UNB11 = 57,
        UNB2_2 = 58,
        UNB2_3 = 59,
        Unb21 = 60,
        UNB3_2 = 61,
        Unb31 = 62,
        UNG_Segment = 63,
        UNG1 = 64,
        Ung21 = 65,
        Ung31 = 66,
        Unh21 = 67,
        Unh22 = 68,
        Unh23 = 69
    }
}
