namespace BREPipelineFramework.SampleInstructions
{
    /// <summary>
    /// See http://technet.microsoft.com/en-us/library/bb245991.aspx for an explanation of the WCF context properties
    /// </summary>
    public enum BizTalkWCFPropertySchemaEnum
    {
        Action = 0,
        AffiliateApplicationName = 1,
        AlgorithmSuite = 2,
        BindingConfiguration = 3,
        BindingType = 4,
        ClientCertificate = 5,
        CloseTimeout = 6,
        CustomDeadLetterQueue = 7,
        DeadLetterQueue = 8,
        DisableLocationOnFailure = 9,
        EnableTransaction = 10,
        EndpointBehaviorConfiguration = 11,
        EstablishSecurityContext = 12,
        FromAddress = 13,
        Headers = 14,
        Identity = 15,
        InboundBodyLocation = 16,
        InboundBodyPathExpression = 17,
        InboundHeaders = 18,
        InboundNodeEncoding = 19,
        IsFault = 20,
        IsolationLevel = 21,
        LeaseTimeout = 22,
        MaxConcurrentCalls = 23,
        MaxConnections = 24,
        MaxReceivedMessageSize = 25,
        MessageClientCredentialType = 26,
        MessageEncoding = 27,
        MsmqAuthenticationMode = 28,
        MsmqEncryptionAlgorithm = 29,
        MsmqProtectionLevel = 30,
        MsmqSecureHashAlgorithm = 31,
        NegotiateServiceCredential = 32,
        OpenTimeout = 33,
        OrderedProcessing = 34,
        OutboundBodyLocation = 35,
        OutboundCustomHeaders = 36,
        OutboundXmlTemplate = 37,
        Password = 38,
        PropagateFaultMessage = 39,
        ProxyAddress = 40,
        ProxyPassword = 41,
        ProxyToUse = 42,
        ProxyUserName = 43,
        ReferencedBindings = 44,
        ReplyToAddress = 45,
        SecurityMode = 46,
        SendTimeout = 47,
        ServiceBehaviorConfiguration = 48,
        ServiceCertificate = 49,
        SuspendMessageOnFailure = 50,
        TextEncoding = 51,
        TimeToLive = 52,
        To = 53,
        TransactionProtocol = 54,
        TransportClientCredentialType = 55,
        TransportProtectionLevel = 56,
        UserName = 57,
        UseSourceJournal = 58,
        UseSSO = 59,
        HttpHeaders = 59,
        HttpMethodAndUrl = 60,
        InboundHttpHeaders = 61,
        InboundHttpMethod = 62,
        InboundHttpStatusCode = 63,
        InboundHttpStatusDescription = 64,
        IssuerName = 65,
        IssuerSecret = 66,
        OutboundHttpStatusCode = 67,
        OutboundHttpStatusDescription = 68,
        StsUri = 69,
        SuppressMessageBodyForHttpVerbs = 70,
        VariablePropertyMapping = 71
    }
}
