using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BREPipelineFramework.SampleInstructions
{
    /// <summary>
    /// See http://msdn.microsoft.com/en-us/library/ee277239(v=bts.10).aspx for an explanation of the BTS context properties
    /// </summary>
    public enum BizTalkGlobalPropertySchemaEnum
    {
        AckDescription = 0,
        AckFailureCategory = 1,
        AckFailureCode = 2,
        AckID = 3,
        AckInboundTransportLocation = 4,
        AckOutboundTransportLocation = 5,
        AckOwnerID = 6,
        AckReceivePortID = 7,
        AckReceivePortName = 8,
        AckRequired = 9,
        AckSendPortID = 10,
        AckSendPortName = 11,
        AckType = 12,
        ActionOnFailure = 13,
        ActivationServiceID = 14,
        AppStreamEnd = 15,
        AppStreamGUID = 16,
        AppStreamN = 17,
        AppStreamPrev = 18,
        BackupEndpointInfo = 19,
        BatchRequired = 20,
        BizTalkControl = 21,
        CorrelationToken = 22,
        DecryptionCert = 23,
        DestinationParty = 24,
        DestinationPartyID = 25,
        DestinationPartyQualifier = 26,
        EncryptionCert = 27,
        EndpointGroup = 28,
        EpmRRCorrelationToken = 29,
        ExpirationTime = 30,
        FaultName = 31,
        FaultQueue = 32,
        InAppStreamEnd = 33,
        InAppStreamGUID = 34,
        InAppStreamN = 35,
        InAppStreamPrev = 36,
        InboundTransportLocation = 37,
        InboundTransportType = 38,
        InterchangeID = 39,
        InterchangeSequenceNumber = 40,
        IsDynamicSend = 41,
        IsFragmented = 42,
        IsRequestResponse = 43,
        IsSolicitResponse = 44,
        JobID = 45,
        LastInterchangeMessage = 46,
        LoopBack = 47,
        LRPMsgBodyTracking = 48,
        LTPMsgBodyTracking = 49,
        MessageDestination = 50,
        MessageExchangePattern = 51,
        MessageID = 52,
        MessageType = 53,
        Operation = 54,
        OutboundTransportCLSID = 55,
        OutboundTransportLocation = 56,
        OutboundTransportType = 57,
        PartnerPort = 58,
        PartnerService = 59,
        PassThrough = 60,
        PipelinesExecuted = 61,
        ProcessingParts = 62,
        PropertiesToUpdate = 63,
        ReceivePipelineConfig = 64,
        ReceivePipelineID = 65,
        ReceivePipelineResponseConfig = 66,
        ReceivePortID = 67,
        ReceivePortName = 68,
        ReceivePortTransformHint = 69,
        ReqRespTransmitPipelineID = 70,
        RetryCount = 71,
        RetryInterval = 72,
        RouteDirectToTP = 73,
        SchemaStrongName = 74,
        SendPipelineConfig = 75,
        SendPipelineResponseConfig = 76,
        SendPortTransformHint = 77,
        SignatureCertificate = 78,
        SigningCert = 79,
        SOAPAction = 80,
        SourceParty = 81,
        SourcePartyEvidence = 82,
        SourcePartyEvidenceQualifier = 83,
        SourcePartyID = 84,
        SourcePartyQualifier = 85,
        SPGroupID = 86,
        SPID = 87,
        SPName = 88,
        SPTransportBackupID = 89,
        SPTransportID = 90,
        SSOTicket = 91,
        SuppressRoutingFailureDiagnosticInfo = 92,
        SuspendAsNonResumable = 93,
        SuspendMessageOnMappingFailure = 94,
        SuspendMessageOnRoutingFailure = 95,
        TransmitPipelineID = 96,
        TransmitWorkID = 97,
        TwoWayReceivePort = 98,
        WindowsUser = 99,
        WorkID = 100
    }
}
